# Generated by Django 5.0.6 on 2025-04-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_category_rename_utworzono_record_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status_color',
            field=models.CharField(choices=[('white', 'Brak statusu'), ('yellow', 'Do zrobienia'), ('red', 'Pilne'), ('green', 'Skończone'), ('blue', 'W trakcie')], default='white', max_length=20),
        ),
    ]
