# Generated by Django 5.0.6 on 2025-04-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_record_status_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
